### ISSUE TITLE
輕聲符號在前面 跟其他一二三四聲不一樣

### ISSUE THREAD

**Issue by b02902131** [Tocknicsu/bopomofo#2]
教育部為什麼要這樣做呢
太令人不解了
這樣就沒辦法靠聲符把注音逐字切開來了
想了很久似乎無解

**Comment by Tocknicsu** [comment]
我已經 upload 一個新的版本，兩個注音之間用空白隔開了，另外關於教育部的注音辭典，裡面有需多規則和我們日常生活中使用的有所落差，使用的時候請多多注意

**Comment by b02902131** [comment]
非常感謝您這麼立即的回覆這個 issue 以及更新！
祝您研究、工作或是任何事情順利、順心
感謝🙏

**Comment by b02902131** [comment]
您好，還是很感謝您的更新
但是檢視並實測過後發現，這樣其實無法逐字切開

`main.py` 中的 `trans_sentense` function
```python
def trans_sentense(text):
    ret = ""
    buf = ""
    for x in text:
        if x not in words:
            ret = ret + ' ' + trans_word(buf)
            buf = ""
            ret = ret + ' ' + trans_word(x)
            continue
        if buf + x not in words:
            ret = ret + ' ' + trans_word(buf)
            buf = x
        else:
            buf = buf + x
    ret = ret + ' ' + trans_word(buf)
    return ret[1:]
```

trace 完 code 之後推測這邊的做法是
1. 依序將下一個 char x 加進 buffer
2. 檢查如果再加一個 char x 還有沒有辦法組成在 words 裡面有收的字串
    1. 如果沒有，就把 buf 先轉成注音存進 ret ，並把 buf 重設為 x
    2. 如果有，就回到第一步驟繼續

另外推測第一個 if 應該是防止出現字典裡沒有的字？如果出現的話就直接把 buf 轉換，char x 直接輸出？

假設我的理解沒有錯的話
如果輸入的字串有長度大於一的子字串是在字典裡查得到的，則他們會一起被 trans_word 處理？

附個例子當參考：
```
print(trans_sentense('做得好'))    # output: ㄗㄨㄛˋ˙ㄉㄜ ㄏㄠˇ
```
* '做得' 有在 words 裡面
* '做得好' 不在 words 裡面
* main.py 程式讀到好的時候，將 '做得' 注音一起輸出
* 做跟得中間沒空格，得跟好中間有空格

因此這樣還是不成功，
但無論如何還是很感謝您的協助！


---
我有想過一個方法是犧牲這些長度大於1的條目的準確性，改成直接逐個 char 餵給 trans_word
這個替代方法可以逐字切開，但似乎犧牲了含破音字的字詞的處理

**Comment by Tocknicsu** [comment]
我將整理字詞的方法更新了一下，現在應該解決了這個問題了！

**Comment by b02902131** [comment]
感謝您！
我昨天也試過重建dict檔案的方法
但一直沒想出好方法重建
因為被輕聲符號的位子卡住
（應該說，如果我能重建dict其實我就也能完成原本的需求）

那我就把這個 issue close 囉

再次感謝您 <(_ _)>
祝您事事順心，健康平安！
