### ISSUE TITLE
請問有辦法擴充字嗎？

### ISSUE THREAD

**Issue by changchichung** [Tocknicsu/bopomofo#4]
我們碰到一些狀況，這些字在教育部國語辭典簡編本裡面找不到
例如 䅞 
是不是有辦法可以擴充來源？或者是自製來源？

**Comment by Tocknicsu** [comment]
可以在目錄底下的 `./extension.dict` 新增自己要的詞喔
如果有大量需求的話可以考慮放盡 `./dict` 底下

**Comment by changchichung** [comment]
感謝回覆！
